import Link from "next/link";
import { ArrowRight, Boxes, Cloud, Coins, Gamepad2, Globe2, ShieldCheck, Sparkles, WalletCards } from "lucide-react";

const products = [
  { icon: Coins, name: "OmniCoin", label: "Ecosystem utility", text: "A proposed access and coordination layer for approved Omni products. No sale or investment flow is enabled in this MVP.", tone: "gold" },
  { icon: Cloud, name: "OmniStorage", label: "Files & data", text: "A creator-first storage experience for project assets, documentation, and game-world content.", tone: "blue" },
  { icon: ShieldCheck, name: "OmniStable", label: "Research sandbox", text: "A compliance-first digital money research concept. No stablecoin, reserve, redemption, or payment product is offered here.", tone: "mint" },
  { icon: Gamepad2, name: "OmniGames", label: "Play & create", text: "Games and digital worlds where utility is experienced through play, not speculation.", tone: "pink" },
  { icon: Globe2, name: "OmniHub", label: "The front door", text: "One account and one clear place to discover approved Omni experiences and their documentation.", tone: "purple" },
];

export default function Home() {
  return <main className="omni-page"><nav className="omni-nav shell"><Link className="omni-brand" href="/"><span className="omni-symbol">O</span><span>Omni<span>Ecosystem</span></span></Link><div className="omni-links"><Link href="#ecosystem">Ecosystem</Link><Link href="#principles">Principles</Link><Link href="/lab">Design Lab</Link></div><Link className="omni-button omni-button-small" href="/start">Enter OmniHub <ArrowRight size={15} /></Link></nav>
    <section className="omni-hero shell"><div className="omni-hero-copy"><div className="omni-kicker"><span className="omni-orbit" /> A utility-first digital ecosystem</div><h1>One ecosystem.<br /><em>Many useful worlds.</em></h1><p>OmniEcosystem brings storage, games, creator tools, and digital coordination into one transparent platform—designed for real utility, tested carefully, and built without promises of profit.</p><div className="omni-actions"><Link className="omni-button" href="/start">Explore OmniHub <ArrowRight size={17} /></Link><Link className="omni-text-link" href="/lab">Open the Design Lab</Link></div><div className="omni-trust"><span><ShieldCheck size={15} /> Reviewable by design</span><span><WalletCards size={15} /> User-controlled</span><span><Boxes size={15} /> Testnet-first</span></div></div><div className="omni-planet"><div className="planet-glow" /><div className="planet"><span>O</span></div><div className="orbit orbit-one" /><div className="orbit orbit-two" /><span className="satellite satellite-one">DATA</span><span className="satellite satellite-two">PLAY</span><span className="satellite satellite-three">HUB</span></div></section>
    <section id="ecosystem" className="omni-ecosystem shell"><div className="omni-section-heading"><div><span className="omni-kicker">THE OMNI MAP</span><h2>Everything connected.<br /><em>Nothing hidden.</em></h2></div><p>Each product has a clear job. Each claim has a boundary. The ecosystem grows only when the foundations deserve it.</p></div><div className="product-grid">{products.map(({ icon: Icon, ...product }) => <article className={`product-card ${product.tone}`} key={product.name}><div className="product-icon"><Icon size={21} /></div><span className="product-label">{product.label}</span><h3>{product.name}</h3><p>{product.text}</p><Link href={product.name === "OmniStable" ? "/terms" : "/start"}>View concept <ArrowRight size={14} /></Link></article>)}</div></section>
    <section id="principles" className="omni-principles"><div className="shell principle-grid"><div><span className="omni-kicker">THE OMNI PROMISE</span><h2>Build something people use.<br /><em>Then prove how it works.</em></h2></div><div className="principles-list"><div><strong>01</strong><span><b>Utility before markets</b> Products must work without a token price.</span></div><div><strong>02</strong><span><b>Transparency before hype</b> Risks, permissions, economics, and limits stay visible.</span></div><div><strong>03</strong><span><b>Review before launch</b> Financial or mainnet features require professional review first.</span></div></div></div></section>
    <section className="omni-cta shell"><div><span className="omni-kicker">START WITH A MODEL</span><h2>Shape the ecosystem<br />before it ships.</h2><p>Use the Omni Design Lab to explore utility, allocation, and risk in a testnet-first workspace.</p></div><Link className="omni-button" href="/lab">Build a scenario <Sparkles size={16} /></Link></section>
    <footer className="omni-footer shell"><Link className="omni-brand" href="/"><span className="omni-symbol">O</span><span>Omni<span>Ecosystem</span></span></Link><span>Concept product · testnet-first · not financial advice</span><Link href="/terms">Product boundaries →</Link></footer>
  </main>;
}
